# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20180903_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='date_created',
        ),
        migrations.AddField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='doing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='to_do',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
