# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20180903_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varieties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varieties', models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], default='Bug', max_length=2)),
            ],
        ),
    ]
