# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='doing',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='done',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='to_do',
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('Doing', 'Doing'), ('Done', 'Done')], default='To do', max_length=40),
        ),
        migrations.AlterField(
            model_name='varieties',
            name='varieties',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], default='Bug', max_length=40),
        ),
    ]
