# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_auto_20180904_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Varieties',
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('Doing', 'Doing'), ('Done', 'Done')], default='To do', max_length=40),
        ),
        migrations.AddField(
            model_name='issue',
            name='varieties',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], default='Bug', max_length=40),
        ),
    ]
