# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_auto_20180904_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
